import { Appointment, Notification } from '../types';

export const dummyAppointments: Appointment[] = [
  {
    id: '1',
    patientName: 'Jay Patil',
    patientId: 'APPLE112349087',
    symptom: 'Hairfall',
    status: 'booked-paid',
    date: '13/09/2023',
    time: '10:30 AM',
    fee: 800,
    type: 'video',
    appointmentType: 'Paid Video',
    bookingStatus: 'Confirmed',
    routineStatus: 'Not Assigned',
    symptoms: {
      symptom: 'Acne',
      description: 'I have acne',
      severity: 'mild',
      duration: '2 days',
      sleepPattern: 'Two-part sleep',
    },
  },
  {
    id: '2',
    patientName: 'Aliana Sen',
    patientId: 'ALIANA987654',
    symptom: 'Hairfall',
    status: 'booked-paid',
    date: '13/09/2023',
    time: '10:30 AM',
    fee: 800,
    type: 'video',
    appointmentType: 'Paid Video',
    bookingStatus: 'Confirmed',
    routineStatus: 'Not Assigned',
  },
  {
    id: '3',
    patientName: 'JP',
    patientId: 'JP112233',
    symptom: 'Headache',
    status: 'doctor-no-show',
    date: '16 Dec, 2024',
    time: '03:29 PM',
    fee: 0,
    type: 'audio',
    appointmentType: 'Free Audio',
    bookingStatus: 'Doctor-No-Show',
    routineStatus: 'Not Assigned',
  },
];

export const dummyNotifications: Notification[] = [
  {
    id: '1',
    title: 'New Appointment',
    message: 'Jay Patil booked an appointment for Hairfall',
    time: '10 min ago',
    read: false,
    type: 'appointment',
  },
  {
    id: '2',
    title: 'Call Reminder',
    message: 'Your call with Aliana Sen starts in 15 minutes',
    time: '1 hour ago',
    read: true,
    type: 'appointment',
  },
  {
    id: '3',
    title: 'System Update',
    message: 'New features added to the doctor portal',
    time: '2 days ago',
    read: false,
    type: 'system',
  },
];